apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: trabajo2
data:
  DB_HOST: "db-svc"
  DB_PORT: "5432"
  DB_NAME: "appdb"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx
  namespace: trabajo2
data:
  default.conf: |
    server {
      listen 80;

      location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
      }

      location /api/ {
        proxy_pass http://backend-svc:3000/;
      }
    }
