apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi # Capacidad máxima del volumen
  accessModes:
    - ReadWriteOnce # Solo un nodo puede montarlo en modo lectura/escritura
  persistentVolumeReclaimPolicy: Retain # Si el PVC se elimina, los datos NO se borran automáticamente
  hostPath:
    path: /data/postgres